/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdi.UI;

import com.backendless.Backendless;
import com.backendless.BackendlessCollection;
import com.backendless.async.callback.AsyncCallback;
import com.backendless.exceptions.BackendlessFault;
import com.backendless.persistence.BackendlessDataQuery;
import com.backendless.persistence.QueryOptions;
import com.backendless.push.BackendlessBroadcastReceiver;
import com.pdi.negocio.entidades.finales.Imputacion;
import com.pdi.util.General;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Sastre
 */
public class CajaVentana extends javax.swing.JInternalFrame {

    /**
     * Creates new form EventoVentana
     */
    //Codigos para referirse a Ingreso/Egreso
    public final static int INGRESO_COD = 1;
    public final static int EGRESO_COD = -1;

    //Atrib para manejar si hay una ventana abierta de este tipo
    public static boolean abierta = false;

    //Titulos para las columnas de la tabla
    private final String[] colName = new String[]{
        "Fecha", "Concepto", "Monto"};

    //Modelo para controlar la info de la tabla
    DefaultTableModel modeloTabla = new DefaultTableModel(null, colName);

    public CajaVentana() {
        initComponents();

        //Relaciona los modelos con las tablas
        imputacionesTbl.setModel(modeloTabla);
        actualizarEtiquetas();
        cargarImputaciones();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        imputacionesTbl = new javax.swing.JTable();
        agregarIngresoBtn = new javax.swing.JButton();
        agregarEgresoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saldoLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        conceptoTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        montoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        estadoLbl = new javax.swing.JLabel();
        cargandoTxt = new javax.swing.JLabel();
        minLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Caja");
        setPreferredSize(new java.awt.Dimension(857, 588));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Flujo de Fondos"));

        imputacionesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Concepto", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(imputacionesTbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        agregarIngresoBtn.setText("Agregar Ingreso");
        agregarIngresoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarIngresoBtnActionPerformed(evt);
            }
        });

        agregarEgresoBtn.setText("Agregar Egreso");
        agregarEgresoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEgresoBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("SALDO:");

        saldoLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        saldoLbl.setText("$0");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Concepto:");

        jLabel5.setText("Monto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("ESTADO:");

        estadoLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        estadoLbl.setText("OK");

        cargandoTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        minLbl.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        minLbl.setText("$0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("MINIMO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conceptoTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(montoTxt))
                    .addComponent(agregarIngresoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(agregarEgresoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cargandoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(minLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(saldoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(saldoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(minLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(estadoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(conceptoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(montoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarIngresoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarEgresoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargandoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarIngresoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarIngresoBtnActionPerformed

        boolean validacionOK = validarForm();

        if (validacionOK) {

            //Si es valida la imputacion en la caja continua
            boolean imputacionOK = VentanaMaestra.CAJA.imputarIngreso(
                    Float.parseFloat(montoTxt.getText()), this);

            if (imputacionOK) {
                //Agrega la imputacion en la tabla y en Backendless
                agregar(INGRESO_COD, this,
                        fechaTxt.getText(), conceptoTxt.getText(), montoTxt.getText());

            }

        }


    }//GEN-LAST:event_agregarIngresoBtnActionPerformed

    private void agregarEgresoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEgresoBtnActionPerformed
        boolean validacionOK = validarForm();

        if (validacionOK) {

            //Si es valida la imputacion en la caja continua
            boolean imputacionOK = VentanaMaestra.CAJA.imputarEgreso(
                    Float.parseFloat(montoTxt.getText()), this);

            if (imputacionOK) {
                //Agrega la imputacion en la tabla y en Backendless
                agregar(EGRESO_COD, this,
                        fechaTxt.getText(), conceptoTxt.getText(), montoTxt.getText());

            }

        }
    }//GEN-LAST:event_agregarEgresoBtnActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        abierta = false;
    }//GEN-LAST:event_formInternalFrameClosed

    public void agregar(int cod, final Component c,
            final String fecha, final String concepto, String monto) {

        cargandoTxt.setText("Guardando imputacion...");

        //Esta variable se declara null para evitar tener que poner todo el codigo
        //en la clausula try, teniendo en cuenta que nunca va a llegar al catch
        //porque la fecha ya fue validada.
        Date fechaImputacion = null;

        //Se pasan los String de monto y fecha a sus respectivas clases
        final float montoImputacion = Float.parseFloat(monto) * cod;
        try {
            fechaImputacion = General.formatoFecha.parse(fecha);
        } catch (ParseException ex) {
            //Nunca se llega aca porque la fecha ya esta validada;
        }

        Imputacion imputacion = new Imputacion();
        imputacion.setMonto(montoImputacion);
        imputacion.setFecha(fechaImputacion);
        imputacion.setConcepto(concepto);

        Backendless.Persistence.save(imputacion, new AsyncCallback<Imputacion>() {

            public void handleResponse(Imputacion t) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(c, //Componente
                        "Imputacion Guardada Correctamente", //Mensaje
                        "Imputacion Guardada", //Titulo
                        JOptionPane.INFORMATION_MESSAGE);
                modeloTabla.addRow(new Object[]{
                    fecha, concepto, montoImputacion});
                actualizarEtiquetas();
                limpiarForm();
            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(c, //Componente
                        "Error: " + bf.getMessage(), //Mensaje
                        "Error al guardar la imputacion", //Titulo
                        JOptionPane.WARNING_MESSAGE); //Imagen 
            }

        });

    }

    private void cargarImputaciones() {
        cargandoTxt.setText("Cargando imputaciones...");

        BackendlessDataQuery dataQuery = new BackendlessDataQuery();
        QueryOptions descOrder = new QueryOptions("created asc");
        dataQuery.setQueryOptions(descOrder);

        Backendless.Persistence.of(Imputacion.class).find(dataQuery, new AsyncCallback<BackendlessCollection<Imputacion>>() {

            public void handleResponse(BackendlessCollection<Imputacion> imputacionesBackendless) {
                cargandoTxt.setText("");
                if (imputacionesBackendless != null) {
                    List<Imputacion> imputacionesList = imputacionesBackendless.getData();
                    for (int i = 0; i < imputacionesList.size(); i++) {
                        Imputacion imp = imputacionesList.get(i);

                        modeloTabla.addRow(new Object[]{
                            General.formatoFecha.format(imp.getFecha()),
                            imp.getConcepto(),
                            imp.getMonto()});

                    }
                }

            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                //Si aun no se cargaron objetos de esta clase, arroja un error
                //conocido por esto. En caso de que se trate de este error el que
                //ocasiono la BackendlessFault esta todo en orden, por lo tanto se
                //saltea.
                if (!bf.getCode().equals(General.COD_SIN_CLASE)) {
                    JOptionPane.showMessageDialog(CajaVentana.this, //Componente
                            bf.getMessage(), //Mensaje
                            "Error al cargar las imputaciones", //Titulo
                            JOptionPane.WARNING_MESSAGE); //Imagen
                }
            }
        });

    }

    private void limpiarForm() {
        fechaTxt.setText("");
        conceptoTxt.setText("");
        montoTxt.setText("");
        imputacionesTbl.clearSelection();

    }

    private void actualizarEtiquetas() {

        minLbl.setText(Float.toString(VentanaMaestra.CAJA.getMinimo()));
        saldoLbl.setText(Float.toString(VentanaMaestra.CAJA.getSaldo()));

        if (VentanaMaestra.CAJA.isMinOK()) {
            estadoLbl.setText("OK");
            estadoLbl.setForeground(Color.BLACK);
        } else {
            float montoMin = VentanaMaestra.CAJA.getMinimo();
            float saldo = VentanaMaestra.CAJA.getSaldo();
            float diferencia = montoMin - saldo;

            estadoLbl.setText("FALTAN $" + diferencia);
            estadoLbl.setForeground(Color.RED);
        }
    }

    private boolean validarForm() {

        //Validar que la fecha no esté vacía
        if (fechaTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "La fecha no puede estar vacia",
                    "Completar Fecha", JOptionPane.WARNING_MESSAGE);
            fechaTxt.requestFocus();
            return false;
        }

        //Validar que la fecha tenga formato dd/MM/yyyy
        try {
            General.formatoFecha.parse(fechaTxt.getText());
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "El formato de fcha de ser DD/MM/AAAA",
                    "Mal formato de fecha", JOptionPane.WARNING_MESSAGE);
            fechaTxt.requestFocus();
            return false;
        }

        //Validar que el concepto no esté vacío
        if (conceptoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "El concepto no puede estar vacio",
                    "Completar Concepto", JOptionPane.WARNING_MESSAGE);
            conceptoTxt.requestFocus();
            return false;
        }

        //Validar que el monto no esté vacío
        if (montoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "El Monto no puede estar vacio",
                    "Completar Monto", JOptionPane.WARNING_MESSAGE);
            montoTxt.requestFocus();
            return false;
        }

        //Validar que el monto sea un numero decimal
        try {
            Float.parseFloat(montoTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El monto debe ser un numero decimal",
                    "Corregir Monto", JOptionPane.WARNING_MESSAGE);
            montoTxt.requestFocus();
            return false;
        }

        //Validar que el monto sea un numero positivo
        if (Float.parseFloat(montoTxt.getText()) < 0) {
            JOptionPane.showMessageDialog(this,
                    "El Monto debe ser un numero positivo. \n"
                    + "Considera ingresar la operacion inversa.",
                    "Corregir Monto", JOptionPane.WARNING_MESSAGE);
            montoTxt.requestFocus();
            return false;
        }

        return true;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEgresoBtn;
    private javax.swing.JButton agregarIngresoBtn;
    private javax.swing.JLabel cargandoTxt;
    private javax.swing.JTextField conceptoTxt;
    private javax.swing.JLabel estadoLbl;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JTable imputacionesTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel minLbl;
    private javax.swing.JTextField montoTxt;
    private javax.swing.JLabel saldoLbl;
    // End of variables declaration//GEN-END:variables

}
