/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdi.UI;

import com.backendless.Backendless;
import com.backendless.BackendlessCollection;
import com.backendless.async.callback.AsyncCallback;
import com.backendless.exceptions.BackendlessFault;
import com.backendless.persistence.BackendlessDataQuery;
import com.pdi.DAO.AliadosDAO;
import com.pdi.DAO.ClientesDAO;
import javax.swing.DefaultListModel;

import com.pdi.negocio.entidades.finales.*;
import com.pdi.util.General;
import com.pdi.negocio.enums.TipoDeEvento;
import com.pdi.negocio.enums.EstadoDeEvento;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sastre
 */
public class EventosVentana extends javax.swing.JInternalFrame {

    /**
     * Creates new form EventoVentana
     */
    //Atrib para manejar si hay una ventana abierta de este tipo
    public static boolean abierta = false;

    //Modelo de la lista de Eventos
    DefaultListModel modeloLista = new DefaultListModel();

    //Modelo del ComboBox de Clientes
    DefaultComboBoxModel<Cliente> modeloComboClientes = new DefaultComboBoxModel<Cliente>();

    //Modelo del ComboBox de Aliados
    DefaultComboBoxModel<Aliado> modeloComboAliados = new DefaultComboBoxModel<Aliado>();

    public EventosVentana() {
        //Pone en verdadero el atrib que controla si la ventana esta abierta
        this.abierta = true;

        //Inicializa los componentes 
        initComponents();
        //Relaciona los modelos con sus elementos
        eventosList.setModel(modeloLista);
        clienteCmb.setModel(modeloComboClientes);
        aliadoCmb.setModel(modeloComboAliados);

        //Carga Todos los Datos
        cargarEventosClientesAliados();
        cargarTiposDeEventos();

        //TODO: cargarAliados();
        cargarEstados();
        System.out.println("Todos los elementos fueron cargados");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoClienteDlg = new javax.swing.JDialog();
        guardarClienteBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        descuentoTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cancelarClienteBtn = new javax.swing.JButton();
        nuevoAliadoDlg = new javax.swing.JDialog();
        guardarAliadoBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nombreATxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        apellidoATxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mailATxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        comisionTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cancelarAliadoBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        comisionAcumuladaTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventosList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        generarPDFBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        guardarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lugarTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        personasTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipoDeEventoCmb = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        nuevoClienteBtn = new javax.swing.JButton();
        clienteCmb = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aliadoCmb = new javax.swing.JComboBox();
        nuevoAliadoBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        precioTxt = new javax.swing.JTextField();
        costoTxt = new javax.swing.JTextField();
        resultadoTxt = new javax.swing.JTextField();
        cotizarBtn = new javax.swing.JButton();
        consumidoBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estadoCmb = new javax.swing.JComboBox();
        pagadoTxt = new javax.swing.JTextField();
        adeudadoTxt = new javax.swing.JTextField();
        generarOrdenDeCompraBtn = new javax.swing.JButton();
        cargandoTxt = new javax.swing.JLabel();

        guardarClienteBtn.setText("Guardar");
        guardarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarClienteBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre:");

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        jLabel14.setText("Apellido");

        jLabel15.setText("Mail:");

        jLabel16.setText("Descuento (%):");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Nuevo Cliente");

        cancelarClienteBtn.setText("Cancelar");
        cancelarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarClienteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoClienteDlgLayout = new javax.swing.GroupLayout(nuevoClienteDlg.getContentPane());
        nuevoClienteDlg.getContentPane().setLayout(nuevoClienteDlgLayout);
        nuevoClienteDlgLayout.setHorizontalGroup(
            nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoClienteDlgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoClienteDlgLayout.createSequentialGroup()
                .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descuentoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                            .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreTxt))
                            .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellidoTxt))
                            .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mailTxt))))
                    .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cancelarClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        nuevoClienteDlgLayout.setVerticalGroup(
            nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoClienteDlgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descuentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(nuevoClienteDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarClienteBtn)
                    .addComponent(guardarClienteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guardarAliadoBtn.setText("Guardar");
        guardarAliadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAliadoBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Nombre:");

        nombreATxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreATxtActionPerformed(evt);
            }
        });

        jLabel19.setText("Apellido");

        jLabel20.setText("Mail:");

        jLabel21.setText("Comision (%):");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Nuevo Aliado");

        cancelarAliadoBtn.setText("Cancelar");
        cancelarAliadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAliadoBtnActionPerformed(evt);
            }
        });

        jLabel23.setText("Comision Acumulada ($):");

        comisionAcumuladaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comisionAcumuladaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoAliadoDlgLayout = new javax.swing.GroupLayout(nuevoAliadoDlg.getContentPane());
        nuevoAliadoDlg.getContentPane().setLayout(nuevoAliadoDlgLayout);
        nuevoAliadoDlgLayout.setHorizontalGroup(
            nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoAliadoDlgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoAliadoDlgLayout.createSequentialGroup()
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comisionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreATxt))
                            .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellidoATxt))
                            .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mailATxt))
                            .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comisionAcumuladaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                    .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(cancelarAliadoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarAliadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        nuevoAliadoDlgLayout.setVerticalGroup(
            nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoAliadoDlgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nombreATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(apellidoATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comisionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comisionAcumuladaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nuevoAliadoDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAliadoBtn)
                    .addComponent(guardarAliadoBtn))
                .addGap(20, 20, 20))
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Eventos");
        setPreferredSize(new java.awt.Dimension(857, 588));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Eventos"));

        eventosList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        eventosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventosListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eventosList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar");
        editarBtn.setEnabled(false);
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.setEnabled(false);
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        generarPDFBtn.setText("Generar PDF");
        generarPDFBtn.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del Evento"));

        guardarBtn.setText("Guardar");
        guardarBtn.setEnabled(false);
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info General"));
        jPanel2.setToolTipText("");

        jLabel2.setText("Lugar:");

        lugarTxt.setEnabled(false);
        lugarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha:");

        fechaTxt.setEnabled(false);

        jLabel4.setText("Cantidad de Personas:");

        personasTxt.setEnabled(false);

        jLabel5.setText("Tiipo de Evento:");

        tipoDeEventoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoDeEventoCmb.setSelectedIndex(-1);
        tipoDeEventoCmb.setToolTipText("");
        tipoDeEventoCmb.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lugarTxt))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personasTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoDeEventoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipoDeEventoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));

        nuevoClienteBtn.setText("Nuevo Cliente");
        nuevoClienteBtn.setEnabled(false);
        nuevoClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoClienteBtnActionPerformed(evt);
            }
        });

        clienteCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clienteCmb.setSelectedIndex(-1);
        clienteCmb.setEnabled(false);

        jLabel3.setText("Cliente:");

        jLabel7.setText("Aliado:");

        aliadoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        aliadoCmb.setSelectedIndex(-1);
        aliadoCmb.setEnabled(false);

        nuevoAliadoBtn.setText("Nuevo Aliado");
        nuevoAliadoBtn.setEnabled(false);
        nuevoAliadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAliadoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clienteCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevoAliadoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aliadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clienteCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(nuevoClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aliadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoAliadoBtn))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Economica"));

        jLabel8.setText("Precio:");

        jLabel10.setText("Costo:");

        jLabel6.setText("Resultado:");

        precioTxt.setEnabled(false);

        costoTxt.setEnabled(false);

        resultadoTxt.setEnabled(false);

        cotizarBtn.setText("Cotizar");
        cotizarBtn.setEnabled(false);

        consumidoBtn.setText("Consumido");
        consumidoBtn.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costoTxt))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consumidoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cotizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cotizarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(costoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consumidoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelarBtn.setText("Cancelar");
        cancelarBtn.setEnabled(false);
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Situacion"));

        jLabel11.setText("Pagado:");

        jLabel12.setText("Estado:");

        jLabel9.setText("Adeudado:");

        estadoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estadoCmb.setSelectedIndex(-1);
        estadoCmb.setEnabled(false);

        pagadoTxt.setEnabled(false);

        adeudadoTxt.setToolTipText("");
        adeudadoTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adeudadoTxt))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagadoTxt))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(estadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pagadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(adeudadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        generarOrdenDeCompraBtn.setText("Generar Orden de Compra");
        generarOrdenDeCompraBtn.setEnabled(false);

        cargandoTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cargandoTxt.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(generarPDFBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generarOrdenDeCompraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cargandoTxt))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(editarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(generarPDFBtn)
                        .addGap(18, 18, 18)
                        .addComponent(generarOrdenDeCompraBtn)
                        .addGap(30, 30, 30)
                        .addComponent(cargandoTxt))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lugarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarTxtActionPerformed

    private void nuevoAliadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAliadoBtnActionPerformed
        nuevoAliadoDlg.setSize(320, 280);
        int largo = this.getWidth() / 2;
        int alto = this.getHeight() / 2;

        int x = largo - (335 / 2);
        int y = alto - (250 / 2);
        nuevoAliadoDlg.setLocation(x, y);

        nuevoAliadoDlg.setVisible(true);
    }//GEN-LAST:event_nuevoAliadoBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarFormulario();
        eventosList.clearSelection();
        habilitarDetalles();
        lugarTxt.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed

        boolean validacionOK = validarForm();
        boolean esNuevo = true;
        if (validacionOK) {
            try {
                Evento e = new Evento();
                Cliente cAnterior = new Cliente();
                Aliado aAnterior = null;
                //Si hay algun evento seleccionado lo utiliza para actualizarlo
                if (eventosList.getSelectedIndex() != -1) {
                    e = (Evento) eventosList.getSelectedValue();
                    esNuevo = false;
                    cAnterior = e.getCliente();
                    aAnterior = e.getAliado();
                }

                Cliente c = (Cliente) clienteCmb.getSelectedItem();

                e.setLugar(lugarTxt.getText());
                e.setFecha(General.formatoFecha.parse(fechaTxt.getText()));
                e.setCantidadDePersonas(Integer.parseInt(personasTxt.getText()));
                e.setTipoDeEvento((TipoDeEvento) tipoDeEventoCmb.getSelectedItem());
                e.setCliente(c);

                if (aliadoCmb.getSelectedIndex() != -1) {
                    e.setAliado((Aliado) aliadoCmb.getSelectedItem());
                }

                e.setPrecio(Float.parseFloat(precioTxt.getText()));

                if (!costoTxt.getText().equals("")) {
                    e.setCosto(Float.parseFloat(costoTxt.getText()));
                }

                if (!resultadoTxt.getText().equals("")) {
                    e.setResultado(Float.parseFloat(resultadoTxt.getText()));
                }

                e.setEstadoDeEvento((EstadoDeEvento) estadoCmb.getSelectedItem());

                if (!pagadoTxt.getText().equals("")) {
                    e.setMontoPagado(Float.parseFloat(pagadoTxt.getText()));
                }

                if (!adeudadoTxt.getText().equals("")) {
                    e.setMontoRestante(Float.parseFloat(adeudadoTxt.getText()));
                }

                if (esNuevo) {
                    agregar(e, this, c, e.getAliado());

                } else {
                    Aliado alyTest = e.getAliado();
                    editar(e, this, c, cAnterior, e.getAliado(), aAnterior);
                }

                deshabilitarDetalles();

            } catch (java.text.ParseException ex) {
                //El codigo nunca deberia llegar aca porque la fecha se testea
                //en validForm()

            }
        }


    }//GEN-LAST:event_guardarBtnActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        abierta = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void eventosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventosListMouseClicked
        limpiarFormulario();
        //Activa los botones correspondientes
        editarBtn.setEnabled(true);
        eliminarBtn.setEnabled(true);
        generarPDFBtn.setEnabled(true);
        generarOrdenDeCompraBtn.setEnabled(true);

        //Obtiene el tiem seleccionado y completa los campos
        Evento e = (Evento) eventosList.getSelectedValue();

        lugarTxt.setText(e.getLugar());
        fechaTxt.setText(General.formatoFecha.format(e.getFecha()));
        personasTxt.setText(Integer.toString(e.getCantidadDePersonas()));
        tipoDeEventoCmb.setSelectedItem(e.getTipoDeEvento());
        Cliente cliente = e.getCliente();
        seleccionarClientePorID(cliente);

        if (e.getAliado() != null) {
            Aliado aliado = e.getAliado();
            seleccionarAliadoPorID(aliado);

        }

        precioTxt.setText(Float.toString(e.getPrecio()));

        if (e.getCosto() != 0) {
            costoTxt.setText(Float.toString(e.getCosto()));
        }

        if (e.getResultado() != 0) {
            resultadoTxt.setText(Float.toString(e.getResultado()));
        }

        estadoCmb.setSelectedItem(e.getEstadoDeEvento());

        if (e.getMontoPagado() != 0) {
            pagadoTxt.setText(Float.toString(e.getMontoPagado()));
        }

        if (e.getMontoRestante() != 0) {
            adeudadoTxt.setText(Float.toString(e.getMontoRestante()));
        }


    }//GEN-LAST:event_eventosListMouseClicked

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        habilitarDetalles();
    }//GEN-LAST:event_editarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        limpiarFormulario();
        eventosList.clearSelection();
        deshabilitarDetalles();
        //Deshabilita los botones restantes
        editarBtn.setEnabled(false);
        eliminarBtn.setEnabled(false);
        generarPDFBtn.setEnabled(false);
        generarOrdenDeCompraBtn.setEnabled(false);


    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        Evento e = (Evento) eventosList.getSelectedValue();

        //Menaje de Confirmacion
        int rta = JOptionPane.showConfirmDialog(this,
                "Confirma que quiere eliminar este evento?:\n" + e.toString(),
                "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);

        if (rta == JOptionPane.NO_OPTION) {
            return;
        } else {
            eliminar(e, this);
            limpiarFormulario();
            eventosList.clearSelection();
            editarBtn.setEnabled(false);
            eliminarBtn.setEnabled(false);
            generarPDFBtn.setEnabled(false);
            generarOrdenDeCompraBtn.setEnabled(false);
        }


    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void nuevoClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoClienteBtnActionPerformed

        nuevoClienteDlg.setSize(335, 250);
        int largo = this.getWidth() / 2;
        int alto = this.getHeight() / 2;

        int x = largo - (335 / 2);
        int y = alto - (250 / 2);
        nuevoClienteDlg.setLocation(x, y);

        //nuevoClienteDlg.setLocationRelativeTo(null);
        nuevoClienteDlg.setVisible(true);


    }//GEN-LAST:event_nuevoClienteBtnActionPerformed

    private void guardarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarClienteBtnActionPerformed
        boolean validacionOK = ClientesDAO.validarForm(this, nombreTxt, apellidoTxt,
                mailTxt, descuentoTxt);

        if (validacionOK) {

            Cliente c = new Cliente();
            c.setNombre(nombreTxt.getText());
            c.setApellido(apellidoTxt.getText());
            c.setMail(mailTxt.getText());
            if (!descuentoTxt.getText().equals("")) {
                c.setDescuento(Float.parseFloat(descuentoTxt.getText()));
            }

            ClientesDAO.agregar(c, this, cargandoTxt, modeloComboClientes, clienteCmb);
            limpiarFormularioClientes();
            nuevoClienteDlg.setVisible(false);

        }


    }//GEN-LAST:event_guardarClienteBtnActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void cancelarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarClienteBtnActionPerformed
        limpiarFormularioClientes();
        nuevoClienteDlg.setVisible(false);
    }//GEN-LAST:event_cancelarClienteBtnActionPerformed

    private void guardarAliadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAliadoBtnActionPerformed
        boolean validacionOK = AliadosDAO.validarForm(this, nombreATxt, apellidoATxt,
                mailATxt, comisionTxt, comisionAcumuladaTxt);

        if (validacionOK) {

            Aliado a = new Aliado();

            a.setNombre(nombreATxt.getText());
            a.setApellido(apellidoATxt.getText());
            a.setMail(mailATxt.getText());

            if (!comisionTxt.getText().equals("")) {
                a.setComisionPorcentaje(Float.parseFloat(comisionTxt.getText()));
            }

            if (!comisionAcumuladaTxt.getText().equals("")) {
                a.setComisionMonto(Float.parseFloat(comisionAcumuladaTxt.getText()));
            }

            AliadosDAO.agregar(a, this, cargandoTxt, modeloComboAliados, aliadoCmb);
            limpiarFormularioAliados();
            nuevoAliadoDlg.setVisible(false);
        }

    }//GEN-LAST:event_guardarAliadoBtnActionPerformed

    private void nombreATxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreATxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreATxtActionPerformed

    private void cancelarAliadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAliadoBtnActionPerformed
        limpiarFormularioAliados();
        nuevoAliadoDlg.setVisible(false);
    }//GEN-LAST:event_cancelarAliadoBtnActionPerformed

    private void comisionAcumuladaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comisionAcumuladaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comisionAcumuladaTxtActionPerformed

    private void habilitarDetalles() {
        lugarTxt.setEnabled(true);
        fechaTxt.setEnabled(true);
        personasTxt.setEnabled(true);
        tipoDeEventoCmb.setEnabled(true);
        clienteCmb.setEnabled(true);
        nuevoClienteBtn.setEnabled(true);
        aliadoCmb.setEnabled(true);
        nuevoAliadoBtn.setEnabled(true);
        precioTxt.setEnabled(true);
        costoTxt.setEnabled(true);
        resultadoTxt.setEnabled(true);
        cotizarBtn.setEnabled(true);
        consumidoBtn.setEnabled(true);
        estadoCmb.setEnabled(true);
        pagadoTxt.setEnabled(true);
        adeudadoTxt.setEnabled(true);
        guardarBtn.setEnabled(true);
        cancelarBtn.setEnabled(true);

    }

    private void deshabilitarDetalles() {
        lugarTxt.setEnabled(false);
        fechaTxt.setEnabled(false);
        personasTxt.setEnabled(false);
        tipoDeEventoCmb.setEnabled(false);
        clienteCmb.setEnabled(false);
        nuevoClienteBtn.setEnabled(false);
        aliadoCmb.setEnabled(false);
        nuevoAliadoBtn.setEnabled(false);
        precioTxt.setEnabled(false);
        costoTxt.setEnabled(false);
        resultadoTxt.setEnabled(false);
        cotizarBtn.setEnabled(false);
        consumidoBtn.setEnabled(false);
        estadoCmb.setEnabled(false);
        pagadoTxt.setEnabled(false);
        adeudadoTxt.setEnabled(false);
        guardarBtn.setEnabled(false);
        cancelarBtn.setEnabled(false);
    }

    private void limpiarFormulario() {
        fechaTxt.setText("");
        lugarTxt.setText("");
        precioTxt.setText("");
        costoTxt.setText("");
        resultadoTxt.setText("");
        pagadoTxt.setText("");
        adeudadoTxt.setText("");
        personasTxt.setText("");
        tipoDeEventoCmb.setSelectedIndex(-1);
        clienteCmb.setSelectedIndex(-1);
        aliadoCmb.setSelectedIndex(-1);
        estadoCmb.setSelectedIndex(-1);

    }

    private void limpiarFormularioClientes() {
        nombreTxt.setText("");
        apellidoTxt.setText("");
        mailTxt.setText("");
        descuentoTxt.setText("");

    }

    private void limpiarFormularioAliados() {
        nombreATxt.setText("");
        apellidoATxt.setText("");
        mailATxt.setText("");
        comisionTxt.setText("");
        comisionAcumuladaTxt.setText("");
    }

    //Guardar el Evento en Parse
    private void agregar(final Evento e, final Component comp,
            final Cliente c, final Aliado a) {
        cargandoTxt.setText("Guardando evento...");

        Backendless.Persistence.save(e, new AsyncCallback<Evento>() {

            public void handleResponse(Evento eventoGuardado) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(comp, //Componente
                        "Evento Guardado Correctamente", //Mensaje
                        "Evento Guardado", //Titulo
                        JOptionPane.INFORMATION_MESSAGE); //Imagen
                e.setObjectId(eventoGuardado.getObjectId());
                e.setUpdated(eventoGuardado.getUpdated());
                e.setCreated(eventoGuardado.getCreated());
                modeloLista.addElement(e);
                eventosList.setSelectedValue(e, true);
                System.out.println("Objeto guardado con ID: " + e.getObjectId());
                ClientesDAO.agregarEvento(comp, c, e);
                if (a != null) {
                    AliadosDAO.agregarEvento(comp, a, e);
                }

            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(comp, //Componente
                        "Error: " + bf.getMessage(), //Mensaje
                        "OTRO! Error al guardar el evento", //Titulo
                        JOptionPane.WARNING_MESSAGE); //Imagen
            }

        });

    }

    //Edita un evento existente (El Evento e tiene que contar con objectID)
    private void editar(final Evento e, final Component comp,
            final Cliente c, final Cliente cAnterior,
            final Aliado a, final Aliado aAnterior) {
        cargandoTxt.setText("Editando evento...");

        Backendless.Persistence.save(e, new AsyncCallback<Evento>() {

            public void handleResponse(Evento eventoGuardado) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(comp, //Componente
                        "Evento Editado Correctamente", //Mensaje
                        "Evento Guardado", //Titulo
                        JOptionPane.INFORMATION_MESSAGE); //Imagen

                System.out.println("Objeto ID: " + e.getObjectId() + " editado");
                eventosList.setSelectedValue(e, true);
                ClientesDAO.modificarEvento(comp, c, cAnterior, e);
                //Si antes no habia un aliado, pero ahora si, le asigna el Evento
                if (aAnterior == null && a != null) {
                    AliadosDAO.agregarEvento(comp, a, e);
                }
                //Si antes habia aliado y ahora tambien, lo modifica
                if (aAnterior != null && a != null) {
                    AliadosDAO.modificarEvento(comp, a, aAnterior, e);

                }
            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(comp, //Componente
                        "Error: " + bf.getMessage(), //Mensaje
                        "AQUI Error al editar el evento", //Titulo
                        JOptionPane.WARNING_MESSAGE); //Imagen
            }

        });

    }

    //Elimina un evento existente a partir de su ID
    private void eliminar(final Evento e, final Component c) {
        cargandoTxt.setText("Eliminando evento...");

        Backendless.Persistence.of(Evento.class).remove(e, new AsyncCallback<Long>() {

            public void handleResponse(Long t) {
                cargandoTxt.setText("");
                System.out.println("Evento con ID: " + e.getObjectId() + " eliminado");
                JOptionPane.showMessageDialog(c, //Componente
                        "Evento Eliminado Correctamente", //Mensaje
                        "Evento Eliminado", //Titulo
                        JOptionPane.INFORMATION_MESSAGE); //Imagen
                modeloLista.removeElement(e);

            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                JOptionPane.showMessageDialog(c, //Componente
                        "Error: " + bf.getMessage(), //Mensaje
                        "Error al eliminar el Evento", //Titulo
                        JOptionPane.WARNING_MESSAGE); //Imagen
            }
        });

    }

    private void cargarTiposDeEventos() {
        tipoDeEventoCmb.setModel(new DefaultComboBoxModel(TipoDeEvento.values()));
        tipoDeEventoCmb.setSelectedIndex(-1);
    }

    private void cargarEstados() {
        estadoCmb.setModel(new DefaultComboBoxModel(EstadoDeEvento.values()));
        estadoCmb.setSelectedIndex(-1);

    }

    private void cargarAliados() {
        cargandoTxt.setText("Cargando Aliados...");

        BackendlessDataQuery query = General.getQueryDepth2();
        Backendless.Persistence.of(Aliado.class).find(query, new AsyncCallback<BackendlessCollection<Aliado>>() {

            public void handleResponse(BackendlessCollection<Aliado> aliadosBackendless) {

                if (aliadosBackendless != null) {
                    ArrayList<Aliado> clientesList = (ArrayList) aliadosBackendless.getData();
                    for (int i = 0; i < clientesList.size(); i++) {
                        Aliado a = clientesList.get(i);
                        modeloComboAliados.addElement(a);
                    }
                    cargandoTxt.setText("");
                    aliadoCmb.setSelectedIndex(-1);
                }
            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                //Si aun no se cargaron objetos de esta clase, arroja un error
                //conocido por esto. En caso de que se trate de este error el que
                //ocasiono la BackendlessFault esta todo en orden, por lo tanto se
                //saltea.
                if (!bf.getCode().equals(General.COD_SIN_CLASE)) {
                    JOptionPane.showMessageDialog(EventosVentana.this, //Componente
                            bf.getMessage(), //Mensaje
                            "Error al cargar los aliados", //Titulo
                            JOptionPane.WARNING_MESSAGE); //Imagen
                }
            }
        });
    }

    private void cargarClientesAliados() {
        cargandoTxt.setText("Cargando Clientes...");

        BackendlessDataQuery query = General.getQueryDepth2();

        Backendless.Persistence.of(Cliente.class).find(query, new AsyncCallback<BackendlessCollection<Cliente>>() {

            public void handleResponse(BackendlessCollection<Cliente> clientesBackendless) {

                if (clientesBackendless != null) {
                    ArrayList<Cliente> clientesList = (ArrayList) clientesBackendless.getData();
                    for (int i = 0; i < clientesList.size(); i++) {
                        Cliente c = clientesList.get(i);
                        modeloComboClientes.addElement(c);
                    }
                    cargandoTxt.setText("");
                    clienteCmb.setSelectedIndex(-1);
                    cargarAliados();
                }
            }

            public void handleFault(BackendlessFault bf) {
                cargandoTxt.setText("");
                //Si aun no se cargaron objetos de esta clase, arroja un error
                //conocido por esto. En caso de que se trate de este error el que
                //ocasiono la BackendlessFault esta todo en orden, por lo tanto se
                //saltea.
                if (!bf.getCode().equals(General.COD_SIN_CLASE)) {
                    JOptionPane.showMessageDialog(EventosVentana.this, //Componente
                            bf.getMessage(), //Mensaje
                            "Error al cargar los clientes", //Titulo
                            JOptionPane.WARNING_MESSAGE); //Imagen
                }
            }
        });
    }

    private void cargarEventosClientesAliados() {
        cargandoTxt.setText("Cargando eventos...");

        BackendlessDataQuery query = General.getQueryDepth2();
        Backendless.Persistence.of(Evento.class).find(query, new AsyncCallback<BackendlessCollection<Evento>>() {

            public void handleResponse(BackendlessCollection<Evento> eventosBackendless) {

                if (eventosBackendless != null) {
                    ArrayList<Evento> eventosList = (ArrayList) eventosBackendless.getData();
                    for (int i = 0; i < eventosList.size(); i++) {
                        Evento e = eventosList.get(i);
                        modeloLista.addElement(e);
                    }
                    cargandoTxt.setText("");
                    cargarClientesAliados();
                }
            }

            public void handleFault(BackendlessFault bf) {

                cargandoTxt.setText("");
                //Si aun no se cargaron objetos de esta clase, arroja un error
                //conocido por esto. En caso de que se trate de este error el que
                //ocasiono la BackendlessFault esta todo en orden, por lo tanto se
                //saltea.
                if (!bf.getCode().equals(General.COD_SIN_CLASE)) {
                    JOptionPane.showMessageDialog(EventosVentana.this, //Componente
                            bf.getMessage(), //Mensaje
                            "Error al cargar los eventos", //Titulo
                            JOptionPane.WARNING_MESSAGE); //Imagen
                }

            }

        });

    }

    private void seleccionarClientePorID(Cliente c) {
        String idObjetivo = c.getObjectId();
        for (int i = 0; i < modeloComboClientes.getSize(); i++) {
            Cliente cl = (Cliente) clienteCmb.getItemAt(i);
            String idIteracion = cl.getObjectId();

            if (idObjetivo.equals(idIteracion)) {
                clienteCmb.setSelectedIndex(i);
                break;
            }

        }
    }

    private void seleccionarAliadoPorID(Aliado a) {
        String idObjetivo = a.getObjectId();
        for (int i = 0; i < modeloComboAliados.getSize(); i++) {
            Aliado al = (Aliado) aliadoCmb.getItemAt(i);
            String idIteracion = al.getObjectId();

            if (idObjetivo.equals(idIteracion)) {
                aliadoCmb.setSelectedIndex(i);
                break;
            }

        }
    }

    //Validar los campos
    private boolean validarForm() {

        //Validar que el lugar no esté vacio
        if (lugarTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "El lugar no puede estar vacio",
                    "Completar Lugar", JOptionPane.WARNING_MESSAGE);
            lugarTxt.requestFocus();
            return false;
        }

        //Validar que la fecha no esté vacía
        if (fechaTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "La fecha no puede estar vacia",
                    "Completar Fecha", JOptionPane.WARNING_MESSAGE);
            fechaTxt.requestFocus();
            return false;
        }

        //Validar que la fecha tenga formato dd/MM/yyyy
        try {
            General.formatoFecha.parse(fechaTxt.getText());
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "El formato de fcha de ser DD/MM/AAAA",
                    "Mal formato de fecha", JOptionPane.WARNING_MESSAGE);
            fechaTxt.requestFocus();
            return false;
        }

        //Validar que la cantidad de personas no esté vacía
        if (personasTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad de personas no puede estar vacia",
                    "Completar Cant de Personas", JOptionPane.WARNING_MESSAGE);
            personasTxt.requestFocus();
            return false;
        }

        //Validar que la cantidad de personas sea un numero entero
        try {
            Integer.parseInt(personasTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad de personas debe ser un numero entero",
                    "Corregir Cant de Personas ", JOptionPane.WARNING_MESSAGE);
            personasTxt.requestFocus();
            return false;
        }

        //Validar que haya un Tipo de Evento Seleccionado
        if (tipoDeEventoCmb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un Tipo de Evento",
                    "Seleccionar Tipo de Evento ", JOptionPane.WARNING_MESSAGE);
            tipoDeEventoCmb.requestFocus();
            return false;
        }

        //Validar que haya un cliente seleccionado
        if (clienteCmb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un Cliente",
                    "Seleccionar Cliente ", JOptionPane.WARNING_MESSAGE);
            clienteCmb.requestFocus();
            return false;
        }

        //Validar que, si hay costo, sea un numero decimal
        if (!costoTxt.getText().equals("")) {
            try {
                Float.parseFloat(costoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El costo debe ser un numero decimal",
                        "Corregir Costo", JOptionPane.WARNING_MESSAGE);
                costoTxt.requestFocus();
                return false;
            }
        }

        //Validar que, si hay resultado, sea un numero decimal
        if (!resultadoTxt.getText().equals("")) {
            try {
                Float.parseFloat(resultadoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El resultado debe ser un numero decimal",
                        "Corregir Resultado", JOptionPane.WARNING_MESSAGE);
                resultadoTxt.requestFocus();
                return false;
            }
        }

        //Validar que, si hay monto pagado, sea un numero decimal
        if (!pagadoTxt.getText().equals("")) {
            try {
                Float.parseFloat(pagadoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El monto pagado debe ser un numero decimal",
                        "Corregir Monto Pagado", JOptionPane.WARNING_MESSAGE);
                pagadoTxt.requestFocus();
                return false;
            }
        }

        //Validar que, si hay adeudado, sea un numero decimal
        if (!adeudadoTxt.getText().equals("")) {
            try {
                Float.parseFloat(adeudadoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El monto adeudado debe ser un numero decimal",
                        "Corregir Monto Adeudado", JOptionPane.WARNING_MESSAGE);
                adeudadoTxt.requestFocus();
                return false;
            }
        }

        //Validar que el precio no este vacio
        if (precioTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "El precio no puede estar vacia. Presione el boton Cotizar"
                    + "para obtener el precio o ingreselo manualmente.",
                    "Cotizar", JOptionPane.WARNING_MESSAGE);
            precioTxt.requestFocus();
            return false;
        }

        //Validar que el precio sea un numero decimal
        try {
            Float.parseFloat(precioTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El precio debe ser un numero decimal",
                    "Corregir Precio ", JOptionPane.WARNING_MESSAGE);
            precioTxt.requestFocus();
            return false;
        }

        //Validar que haya un Estado seleccionado
        if (estadoCmb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un Estado para el evento",
                    "Seleccionar Estado", JOptionPane.WARNING_MESSAGE);
            tipoDeEventoCmb.requestFocus();
            return false;
        }

        return true;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adeudadoTxt;
    private javax.swing.JComboBox aliadoCmb;
    private javax.swing.JTextField apellidoATxt;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JButton cancelarAliadoBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton cancelarClienteBtn;
    private javax.swing.JLabel cargandoTxt;
    private javax.swing.JComboBox clienteCmb;
    private javax.swing.JTextField comisionAcumuladaTxt;
    private javax.swing.JTextField comisionTxt;
    private javax.swing.JButton consumidoBtn;
    private javax.swing.JTextField costoTxt;
    private javax.swing.JButton cotizarBtn;
    private javax.swing.JTextField descuentoTxt;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JComboBox estadoCmb;
    private javax.swing.JList eventosList;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton generarOrdenDeCompraBtn;
    private javax.swing.JButton generarPDFBtn;
    private javax.swing.JButton guardarAliadoBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JButton guardarClienteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lugarTxt;
    private javax.swing.JTextField mailATxt;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField nombreATxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton nuevoAliadoBtn;
    private javax.swing.JDialog nuevoAliadoDlg;
    private javax.swing.JButton nuevoClienteBtn;
    private javax.swing.JDialog nuevoClienteDlg;
    private javax.swing.JTextField pagadoTxt;
    private javax.swing.JTextField personasTxt;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JTextField resultadoTxt;
    private javax.swing.JComboBox tipoDeEventoCmb;
    // End of variables declaration//GEN-END:variables

}
