/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdi.UI;

import javax.swing.DefaultListModel;
import org.parse4j.ParseException;
import org.parse4j.ParseObject;
import org.parse4j.callback.SaveCallback;
import com.pdi.negocio.entidades.finales.*;
import com.pdi.util.General;
import com.pdi.negocio.enums.TipoDeEvento;
import com.pdi.negocio.enums.EstadoDeEvento;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
import org.parse4j.ParseQuery;
import org.parse4j.callback.DeleteCallback;
import org.parse4j.callback.FindCallback;
import org.parse4j.callback.GetCallback;

/**
 *
 * @author Marcos Sastre
 */
public class EventosVentana extends javax.swing.JInternalFrame {

    /**
     * Creates new form EventoVentana
     */
    //Atrib para manejar si hay una ventana abierta de este tipo
    public static boolean abierta = false;

    DefaultListModel modeloLista = new DefaultListModel();

    public EventosVentana() {
        //Pone en verdadero el atrib que controla si la ventana esta abierta
        this.abierta = true;

        //Inicializa los componentes 
        initComponents();
        eventosList.setModel(modeloLista);
        //Carga Todos los Datos
        cargarEventos();
        cargarTiposDeEventos();
        //cargarClientes();
        //cargarAliados();
        cargarEstados();
        System.out.println("Todos los elementos fueron cargados");
        //Relaciona el modelo con la lista

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventosList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        generarPDFBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        guardarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lugarTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        personasTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipoDeEventoCmb = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        nuevoClienteBtn = new javax.swing.JButton();
        clienteCmb = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aliadoCmb = new javax.swing.JComboBox();
        nuevoAliadoBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        precioTxt = new javax.swing.JTextField();
        costoTxt = new javax.swing.JTextField();
        resultadoTxt = new javax.swing.JTextField();
        cotizarBtn = new javax.swing.JButton();
        consumidoBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estadoCmb = new javax.swing.JComboBox();
        pagadoTxt = new javax.swing.JTextField();
        adeudadoTxt = new javax.swing.JTextField();
        generarOrdenDeCompraBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Eventos");
        setPreferredSize(new java.awt.Dimension(857, 588));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Eventos"));

        eventosList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        eventosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventosListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eventosList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar");
        editarBtn.setEnabled(false);
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.setEnabled(false);
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        generarPDFBtn.setText("Generar PDF");
        generarPDFBtn.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del Evento"));

        guardarBtn.setText("Guardar");
        guardarBtn.setEnabled(false);
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info General"));
        jPanel2.setToolTipText("");

        jLabel2.setText("Lugar:");

        lugarTxt.setEnabled(false);
        lugarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha:");

        fechaTxt.setEnabled(false);

        jLabel4.setText("Cantidad de Personas:");

        personasTxt.setEnabled(false);

        jLabel5.setText("Tiipo de Evento:");

        tipoDeEventoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoDeEventoCmb.setSelectedIndex(-1);
        tipoDeEventoCmb.setToolTipText("");
        tipoDeEventoCmb.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lugarTxt))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personasTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoDeEventoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lugarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipoDeEventoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));

        nuevoClienteBtn.setText("Nuevo Cliente");
        nuevoClienteBtn.setEnabled(false);

        clienteCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clienteCmb.setSelectedIndex(-1);
        clienteCmb.setEnabled(false);

        jLabel3.setText("Cliente:");

        jLabel7.setText("Aliado:");

        aliadoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        aliadoCmb.setSelectedIndex(-1);
        aliadoCmb.setEnabled(false);

        nuevoAliadoBtn.setText("Nuevo Aliado");
        nuevoAliadoBtn.setEnabled(false);
        nuevoAliadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAliadoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clienteCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevoAliadoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aliadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clienteCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(nuevoClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aliadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoAliadoBtn))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Economica"));

        jLabel8.setText("Precio:");

        jLabel10.setText("Costo:");

        jLabel6.setText("Resultado:");

        precioTxt.setEnabled(false);

        costoTxt.setEnabled(false);

        resultadoTxt.setEnabled(false);

        cotizarBtn.setText("Cotizar");
        cotizarBtn.setEnabled(false);

        consumidoBtn.setText("Consumido");
        consumidoBtn.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costoTxt))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consumidoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cotizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cotizarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(costoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consumidoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelarBtn.setText("Cancelar");
        cancelarBtn.setEnabled(false);
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Situacion"));

        jLabel11.setText("Pagado:");

        jLabel12.setText("Estado:");

        jLabel9.setText("Adeudado:");

        estadoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estadoCmb.setSelectedIndex(-1);
        estadoCmb.setEnabled(false);

        pagadoTxt.setEnabled(false);

        adeudadoTxt.setToolTipText("");
        adeudadoTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adeudadoTxt))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagadoTxt))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(estadoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pagadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(adeudadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        generarOrdenDeCompraBtn.setText("Generar Orden de Compra");
        generarOrdenDeCompraBtn.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generarPDFBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generarOrdenDeCompraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(editarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(generarPDFBtn)
                        .addGap(18, 18, 18)
                        .addComponent(generarOrdenDeCompraBtn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lugarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarTxtActionPerformed

    private void nuevoAliadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAliadoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoAliadoBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarFormulario();
        habilitarDetalles();
        lugarTxt.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed

        boolean validacionOK = validarForm();
        boolean esNuevo = true;
        if (validacionOK) {
            try {
                Evento e = new Evento();

                //Si hay algun evento seleccionado lo utiliza para actualizarlo
                if (eventosList.getSelectedIndex() != -1) {
                    e = (Evento) eventosList.getSelectedValue();
                    esNuevo = false;
                }

                e.setLugar(lugarTxt.getText());
                e.setFecha(General.formatoFecha.parse(fechaTxt.getText()));
                e.setCantidadDePersonas(Integer.parseInt(personasTxt.getText()));
                e.setTipoDeEvento((TipoDeEvento) tipoDeEventoCmb.getSelectedItem());
                //e.setCliente((Cliente) clienteCmb.getSelectedItem());

                if (aliadoCmb.getSelectedIndex() != -1) {
                    e.setAliado((Aliado) aliadoCmb.getSelectedItem());
                }

                e.setPrecio(Float.parseFloat(precioTxt.getText()));

                if (!costoTxt.getText().equals("")) {
                    e.setCosto(Float.parseFloat(costoTxt.getText()));
                }

                if (!resultadoTxt.getText().equals("")) {
                    e.setResultado(Float.parseFloat(resultadoTxt.getText()));
                }

                e.setEstadoDeEvento((EstadoDeEvento) estadoCmb.getSelectedItem());

                if (!pagadoTxt.getText().equals("")) {
                    e.setMontoPagado(Float.parseFloat(pagadoTxt.getText()));
                }

                if (!adeudadoTxt.getText().equals("")) {
                    e.setMontoRestante(Float.parseFloat(adeudadoTxt.getText()));
                }

                if (esNuevo) {
                    agregar(e, this);

                } else {
                    editar(e, this);
                }
                eventosList.setSelectedValue(e, true);
                deshabilitarDetalles();

            } catch (java.text.ParseException ex) {
                //El codigo nunca deberia llegar aca porque la fecha se testea
                //en validForm()

            }
        }


    }//GEN-LAST:event_guardarBtnActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        abierta = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void eventosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventosListMouseClicked
        //Activa los botones correspondientes
        editarBtn.setEnabled(true);
        eliminarBtn.setEnabled(true);
        generarPDFBtn.setEnabled(true);
        generarOrdenDeCompraBtn.setEnabled(true);

        //Obtiene el tiem seleccionado y completa los campos
        Evento e = (Evento) eventosList.getSelectedValue();

        lugarTxt.setText(e.getLugar());
        fechaTxt.setText(General.formatoFecha.format(e.getFecha()));
        personasTxt.setText(Integer.toString(e.getCantidadDePersonas()));
        tipoDeEventoCmb.setSelectedItem(e.getTipoDeEvento());
        //eventoParse.performOperation("cliente", null);
        //eventoParse.performOperation("aliado", null);
        precioTxt.setText(Float.toString(e.getPrecio()));

        if (e.getCosto() != 0) {
            costoTxt.setText(Float.toString(e.getCosto()));
        }

        if (e.getResultado() != 0) {
            resultadoTxt.setText(Float.toString(e.getResultado()));
        }

        estadoCmb.setSelectedItem(e.getEstadoDeEvento());

        if (e.getMontoPagado() != 0) {
            pagadoTxt.setText(Float.toString(e.getMontoPagado()));
        }

        if (e.getMontoRestante() != 0) {
            adeudadoTxt.setText(Float.toString(e.getMontoRestante()));
        }


    }//GEN-LAST:event_eventosListMouseClicked

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        habilitarDetalles();
    }//GEN-LAST:event_editarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        limpiarFormulario();
        deshabilitarDetalles();
        //Deshabilita los botones restantes
        editarBtn.setEnabled(false);
        eliminarBtn.setEnabled(false);
        generarPDFBtn.setEnabled(false);
        generarOrdenDeCompraBtn.setEnabled(false);


    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        Evento e = (Evento) eventosList.getSelectedValue();
        
        //Menaje de Confirmacion
        int rta = JOptionPane.showConfirmDialog(this,
                    "Confirma que quiere eliminar este evento?:\n" + e.toString(),
                    "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        
        if(rta == JOptionPane.NO_OPTION){
            return;
        }else{
            eliminar(e, this);
            editarBtn.setEnabled(false);
            eliminarBtn.setEnabled(false);
            generarPDFBtn.setEnabled(false);
            generarOrdenDeCompraBtn.setEnabled(false);
        }
        
        
        
        
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void habilitarDetalles() {
        lugarTxt.setEnabled(true);
        fechaTxt.setEnabled(true);
        personasTxt.setEnabled(true);
        tipoDeEventoCmb.setEnabled(true);
        clienteCmb.setEnabled(true);
        nuevoClienteBtn.setEnabled(true);
        aliadoCmb.setEnabled(true);
        nuevoAliadoBtn.setEnabled(true);
        precioTxt.setEnabled(true);
        costoTxt.setEnabled(true);
        resultadoTxt.setEnabled(true);
        cotizarBtn.setEnabled(true);
        consumidoBtn.setEnabled(true);
        estadoCmb.setEnabled(true);
        pagadoTxt.setEnabled(true);
        adeudadoTxt.setEnabled(true);
        guardarBtn.setEnabled(true);
        cancelarBtn.setEnabled(true);

    }

    private void deshabilitarDetalles() {
        lugarTxt.setEnabled(false);
        fechaTxt.setEnabled(false);
        personasTxt.setEnabled(false);
        tipoDeEventoCmb.setEnabled(false);
        clienteCmb.setEnabled(false);
        nuevoClienteBtn.setEnabled(false);
        aliadoCmb.setEnabled(false);
        nuevoAliadoBtn.setEnabled(false);
        precioTxt.setEnabled(false);
        costoTxt.setEnabled(false);
        resultadoTxt.setEnabled(false);
        cotizarBtn.setEnabled(false);
        consumidoBtn.setEnabled(false);
        estadoCmb.setEnabled(false);
        pagadoTxt.setEnabled(false);
        adeudadoTxt.setEnabled(false);
        guardarBtn.setEnabled(false);
        cancelarBtn.setEnabled(false);
    }

    private void limpiarFormulario() {
        fechaTxt.setText("");
        lugarTxt.setText("");
        precioTxt.setText("");
        costoTxt.setText("");
        resultadoTxt.setText("");
        pagadoTxt.setText("");
        adeudadoTxt.setText("");
        personasTxt.setText("");
        tipoDeEventoCmb.setSelectedIndex(-1);
        clienteCmb.setSelectedIndex(-1);
        aliadoCmb.setSelectedIndex(-1);
        estadoCmb.setSelectedIndex(-1);

    }

    //Guardar el Evento en Parse
    private void agregar(final Evento e, final Component c) {

        final ParseObject eventoParse = new ParseObject("Eventos");

        eventoParse.put("lugar", e.getLugar());
        eventoParse.put("fecha", e.getFecha());
        eventoParse.put("personas", e.getCantidadDePersonas());
        eventoParse.put("tipoDeEvento", e.getTipoDeEvento().getCod());
        //eventoParse.performOperation("cliente", null);
        //eventoParse.performOperation("aliado", null);
        eventoParse.put("precio", e.getPrecio());

        if (e.getCosto() != 0) {
            eventoParse.put("costo", e.getCosto());
        }

        if (e.getResultado() != 0) {
            eventoParse.put("resultado", e.getResultado());
        }

        eventoParse.put("estado", e.getEstadoDeEvento().getCod());

        if (e.getMontoPagado() != 0) {
            eventoParse.put("montoPagado", e.getMontoPagado());
        }

        if (e.getMontoRestante() != 0) {
            eventoParse.put("montoRestante", e.getMontoRestante());
        }

        eventoParse.saveInBackground(new SaveCallback() {

            @Override
            public void done(ParseException parseException) {

                if (parseException == null) {
                    JOptionPane.showMessageDialog(c, //Componente
                            "Evento Guardado Correctamente", //Mensaje
                            "Evento Guardado", //Titulo
                            JOptionPane.INFORMATION_MESSAGE); //Imagen
                    e.setId(eventoParse.getObjectId());
                    modeloLista.addElement(e);
                    System.out.println("Objeto guardado con ID: " + e.getId());
                } else {
                    JOptionPane.showMessageDialog(c, //Componente
                            "Error: " + parseException.toString(), //Mensaje
                            "Error al guardar el evento", //Titulo
                            JOptionPane.WARNING_MESSAGE); //Imagen

                }
            }

        });

    }

    //Edita un evento existente a partir de su ID
    private void editar(final Evento e, final Component c) {

        ParseQuery<ParseObject> query = ParseQuery.getQuery("Eventos");
        query.getInBackground(e.getId(), new GetCallback<ParseObject>() {

            @Override
            public void done(ParseObject eventoParse, ParseException parseException) {
                if (parseException == null) {
                    if (eventoParse != null) {

                        eventoParse.put("lugar", e.getLugar());
                        eventoParse.put("fecha", e.getFecha());
                        eventoParse.put("personas", e.getCantidadDePersonas());
                        eventoParse.put("tipoDeEvento", e.getTipoDeEvento().getCod());
                        //eventoParse.performOperation("cliente", null);
                        //eventoParse.performOperation("aliado", null);
                        eventoParse.put("precio", e.getPrecio());

                        if (e.getCosto() != 0) {
                            eventoParse.put("costo", e.getCosto());
                        }

                        if (e.getResultado() != 0) {
                            eventoParse.put("resultado", e.getResultado());
                        }

                        eventoParse.put("estado", e.getEstadoDeEvento().getCod());

                        if (e.getMontoPagado() != 0) {
                            eventoParse.put("montoPagado", e.getMontoPagado());
                        }

                        if (e.getMontoRestante() != 0) {
                            eventoParse.put("montoRestante", e.getMontoRestante());
                        }

                        eventoParse.saveInBackground(new SaveCallback() {

                            @Override
                            public void done(ParseException parseException) {

                                if (parseException == null) {
                                    JOptionPane.showMessageDialog(c, //Componente
                                            "Evento Guardado Correctamente", //Mensaje
                                            "Evento Guardado", //Titulo
                                            JOptionPane.INFORMATION_MESSAGE); //Imagen

                                    System.out.println("Objeto ID: " + e.getId() + "editado");
                                } else {
                                    JOptionPane.showMessageDialog(c, //Componente
                                            "Error: " + parseException.toString(), //Mensaje
                                            "Error al guardar el evento", //Titulo
                                            JOptionPane.WARNING_MESSAGE); //Imagen

                                }
                            }

                        });

                    } else {
                        JOptionPane.showMessageDialog(c, //Componente
                                "No se econtro el evento en la base de datos", //Mensaje
                                "Evento No Encontrado", //Titulo
                                JOptionPane.WARNING_MESSAGE); //Imagen
                    }

                } else {
                    JOptionPane.showMessageDialog(c, //Componente
                            parseException.toString(), //Mensaje
                            "Error al Editar Evento", //Titulo
                            JOptionPane.INFORMATION_MESSAGE); //Imagen
                }

            }
        });

    }
    
    //Elimina un evento existente a partir de su ID
    private void eliminar(final Evento e, final Component c){
        
        ParseQuery<ParseObject> query = ParseQuery.getQuery("Eventos");
        query.getInBackground(e.getId(), new GetCallback<ParseObject>() {

            @Override
            public void done(ParseObject eventoParse, ParseException parseException) {
                eventoParse.deleteInBackground(new DeleteCallback() {

                    @Override
                    public void done(ParseException parseException) {
                        if(parseException==null){
                            JOptionPane.showMessageDialog(c, //Componente
                                            "Evento Eliminado Correctamente", //Mensaje
                                            "Evento Eliminado", //Titulo
                                            JOptionPane.INFORMATION_MESSAGE); //Imagen
                            modeloLista.removeElement(e);
                        }
                    }
                });
            }
            
        });
        
    }

    private void cargarTiposDeEventos() {
        tipoDeEventoCmb.setModel(new DefaultComboBoxModel(TipoDeEvento.values()));
        tipoDeEventoCmb.setSelectedIndex(-1);
    }

    private void cargarEstados() {
        estadoCmb.setModel(new DefaultComboBoxModel(EstadoDeEvento.values()));
        estadoCmb.setSelectedIndex(-1);

    }

    private void cargarEventos() {
        ParseQuery<ParseObject> query = ParseQuery.getQuery("Eventos");

        final Component c = this;
        query.findInBackground(new FindCallback<ParseObject>() {

            @Override
            public void done(List<ParseObject> eventosParse, ParseException parseException) {
                if (parseException == null) {

                    if (eventosParse != null) {

                        for (int i = 0; i < eventosParse.size(); i++) {
                            ParseObject eventoParse = eventosParse.get(i);
                            Evento e = new Evento();

                            e.setId(eventoParse.getObjectId());
                            e.setLugar(eventoParse.getString("lugar"));
                            e.setFecha(eventoParse.getDate("fecha"));
                            e.setCantidadDePersonas(eventoParse.getInt("personas"));
                            e.setTipoDeEvento(TipoDeEvento.getFromInt(eventoParse.getInt("tipoDeEvento")));
                            //e.setCliente(null);
                            //e.setAliado(null);
                            e.setPrecio((float) eventoParse.getDouble("precio"));

                            if (eventoParse.getDouble("costo") != 0) {
                                e.setCosto((float) eventoParse.getDouble("costo"));
                            }

                            if (eventoParse.getDouble("resultado") != 0) {
                                e.setResultado((float) eventoParse.getDouble("resultado"));
                            }

                            e.setEstadoDeEvento(EstadoDeEvento.getFromInt(
                                    eventoParse.getInt("estado")));

                            if (eventoParse.getDouble("montoPagado") != 0) {
                                e.setMontoPagado((float) eventoParse.getDouble("montoPagado"));
                            }

                            if (eventoParse.getDouble("montoRestante") != 0) {
                                e.setMontoRestante((float) eventoParse.getDouble("montoRestante"));
                            }

                            modeloLista.addElement(e);

                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(c, //Componente
                            "Error: " + parseException.toString(), //Mensaje
                            "Error al cargar los eventos", //Titulo
                            JOptionPane.WARNING_MESSAGE); //Imagen
                }
            }
        });

    }

    //Validar los campos
    private boolean validarForm() {

        //Validar que el lugar no esté vacio
        if (lugarTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "El lugar no puede estar vacio",
                    "Completar Lugar", JOptionPane.WARNING_MESSAGE);
            lugarTxt.requestFocus();
            return false;
        }

        //Validar que la fecha no esté vacía
        if (fechaTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "La fecha no puede estar vacia",
                    "Completar Fecha", JOptionPane.WARNING_MESSAGE);
            fechaTxt.requestFocus();
            return false;
        }

        //Validar que la fecha tenga formato dd/MM/yyyy
        try {
            General.formatoFecha.parse(fechaTxt.getText());
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "El formato de fcha de ser DD/MM/AAAA",
                    "Mal formato de fecha", JOptionPane.WARNING_MESSAGE);
            fechaTxt.requestFocus();
            return false;
        }

        //Validar que la cantidad de personas no esté vacía
        if (personasTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad de personas no puede estar vacia",
                    "Completar Cant de Personas", JOptionPane.WARNING_MESSAGE);
            personasTxt.requestFocus();
            return false;
        }

        //Validar que la cantidad de personas sea un numero entero
        try {
            Integer.parseInt(personasTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad de personas debe ser un numero entero",
                    "Corregir Cant de Personas ", JOptionPane.WARNING_MESSAGE);
            personasTxt.requestFocus();
            return false;
        }

        //Validar que haya un Tipo de Evento Seleccionado
        if (tipoDeEventoCmb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un Tipo de Evento",
                    "Seleccionar Tipo de Evento ", JOptionPane.WARNING_MESSAGE);
            tipoDeEventoCmb.requestFocus();
            return false;
        }

        //Validar que haya un cliente seleccionado
        if (clienteCmb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un Cliente",
                    "Seleccionar Cliente ", JOptionPane.WARNING_MESSAGE);
            clienteCmb.requestFocus();
            return false;
        }

        //Validar que, si hay costo, sea un numero decimal
        if (!costoTxt.getText().equals("")) {
            try {
                Float.parseFloat(costoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El costo debe ser un numero decimal",
                        "Corregir Costo", JOptionPane.WARNING_MESSAGE);
                costoTxt.requestFocus();
                return false;
            }
        }

        //Validar que, si hay resultado, sea un numero decimal
        if (!resultadoTxt.getText().equals("")) {
            try {
                Float.parseFloat(resultadoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El resultado debe ser un numero decimal",
                        "Corregir Resultado", JOptionPane.WARNING_MESSAGE);
                resultadoTxt.requestFocus();
                return false;
            }
        }

        //Validar que, si hay monto pagado, sea un numero decimal
        if (!pagadoTxt.getText().equals("")) {
            try {
                Float.parseFloat(pagadoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El monto pagado debe ser un numero decimal",
                        "Corregir Monto Pagado", JOptionPane.WARNING_MESSAGE);
                pagadoTxt.requestFocus();
                return false;
            }
        }

        //Validar que, si hay adeudado, sea un numero decimal
        if (!adeudadoTxt.getText().equals("")) {
            try {
                Float.parseFloat(adeudadoTxt.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El monto adeudado debe ser un numero decimal",
                        "Corregir Monto Adeudado", JOptionPane.WARNING_MESSAGE);
                adeudadoTxt.requestFocus();
                return false;
            }
        }

        //Validar que el precio no este vacio
        if (precioTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "El precio no puede estar vacia. Presione el boton Cotizar"
                    + "para obtener el precio o ingreselo manualmente.",
                    "Cotizar", JOptionPane.WARNING_MESSAGE);
            precioTxt.requestFocus();
            return false;
        }

        //Validar que el precio sea un numero decimal
        try {
            Float.parseFloat(precioTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El precio debe ser un numero decimal",
                    "Corregir Precio ", JOptionPane.WARNING_MESSAGE);
            precioTxt.requestFocus();
            return false;
        }

        //Validar que haya un Estado seleccionado
        if (estadoCmb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un Estado para el evento",
                    "Seleccionar Estado", JOptionPane.WARNING_MESSAGE);
            tipoDeEventoCmb.requestFocus();
            return false;
        }

        return true;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adeudadoTxt;
    private javax.swing.JComboBox aliadoCmb;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JComboBox clienteCmb;
    private javax.swing.JButton consumidoBtn;
    private javax.swing.JTextField costoTxt;
    private javax.swing.JButton cotizarBtn;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JComboBox estadoCmb;
    private javax.swing.JList eventosList;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton generarOrdenDeCompraBtn;
    private javax.swing.JButton generarPDFBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lugarTxt;
    private javax.swing.JButton nuevoAliadoBtn;
    private javax.swing.JButton nuevoClienteBtn;
    private javax.swing.JTextField pagadoTxt;
    private javax.swing.JTextField personasTxt;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JTextField resultadoTxt;
    private javax.swing.JComboBox tipoDeEventoCmb;
    // End of variables declaration//GEN-END:variables

}
