/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdi.UI;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import com.backendless.exceptions.BackendlessFault;
import com.pdi.negocio.entidades.finales.PreciosBase;
import com.pdi.negocio.entidades.finales.VariablesCotizacion;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class VariablesCotizacionVentana extends javax.swing.JInternalFrame {

    /**
     * Creates new form PreciosBaseVentana
     */
    //Atrib para manejar si hay una ventana abierta de este tipo
    public static boolean abierta = false;

    public VariablesCotizacionVentana() {
        //Pone en verdadero el atrib que controla si la ventana esta abierta
        this.abierta = true;

        initComponents();
        cargarVARS_COTIZ();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gananciaFijoTxt = new javax.swing.JTextField();
        gananciaVariableTxt = new javax.swing.JTextField();
        tasaRecargoTxt = new javax.swing.JTextField();
        factorPromoTxt = new javax.swing.JTextField();
        fleteLocalTxt = new javax.swing.JTextField();
        fleteAfueraTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VARIABLES COTIZACION");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ganancia  (fijo):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ganancia (variable):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("% Recargo diario (por mes) hasta el evento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Factor sobre bebias a comprar para promo:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Costo del Flete (Fuera de Venado):");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Costo del Flete (En Venado):");

        gananciaFijoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaFijoTxtActionPerformed(evt);
            }
        });

        tasaRecargoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasaRecargoTxtActionPerformed(evt);
            }
        });

        guardarBtn.setText("GUARDAR");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tasaRecargoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fleteAfueraTxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(factorPromoTxt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(gananciaFijoTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(gananciaVariableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fleteLocalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gananciaFijoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gananciaVariableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tasaRecargoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(factorPromoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fleteLocalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fleteAfueraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gananciaFijoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaFijoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaFijoTxtActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        this.abierta = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed

        VentanaMaestra.VARS_COTIZ.setFactorPromo(Float.parseFloat(factorPromoTxt.getText()));
        VentanaMaestra.VARS_COTIZ.setTasaRecargo(Float.parseFloat(tasaRecargoTxt.getText()));
        VentanaMaestra.VARS_COTIZ.setGananciaVariable(Float.parseFloat(gananciaVariableTxt.getText()));
        VentanaMaestra.VARS_COTIZ.setGananciaFijo(Float.parseFloat(gananciaFijoTxt.getText()));
        VentanaMaestra.VARS_COTIZ.setFleteLocal(Float.parseFloat(fleteLocalTxt.getText()));
        VentanaMaestra.VARS_COTIZ.setFleteAfuera(Float.parseFloat(fleteAfueraTxt.getText()));

        Backendless.Persistence.of(VariablesCotizacion.class).save(VentanaMaestra.VARS_COTIZ,
                new AsyncCallback<VariablesCotizacion>() {

                    public void handleResponse(VariablesCotizacion t) {
                        JOptionPane.showMessageDialog(VariablesCotizacionVentana.this, //Componente
                                "Se modificaron las variables de cotizacion correctamente.", //Mensaje
                                "Variables Cotizacion Modificados", //Titulo
                                JOptionPane.INFORMATION_MESSAGE); //Imagen
                    }

                    public void handleFault(BackendlessFault bf) {
                        JOptionPane.showMessageDialog(VariablesCotizacionVentana.this, //Componente
                                "Error: " + bf.getMessage(), //Mensaje
                                "Error al modificar las Variables de Cotizacion", //Titulo
                                JOptionPane.WARNING_MESSAGE); //Imagen  
                    }
                });

    }//GEN-LAST:event_guardarBtnActionPerformed

    private void tasaRecargoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasaRecargoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tasaRecargoTxtActionPerformed

    private void cargarVARS_COTIZ() {

        factorPromoTxt.setText(Float.toString(VentanaMaestra.VARS_COTIZ.getFactorPromo()));
        tasaRecargoTxt.setText(Float.toString(VentanaMaestra.VARS_COTIZ.getTasaRecargo()));
        gananciaVariableTxt.setText(Float.toString(VentanaMaestra.VARS_COTIZ.getGananciaVariable()));
        gananciaFijoTxt.setText(Float.toString(VentanaMaestra.VARS_COTIZ.getGananciaFijo()));
        fleteLocalTxt.setText(Float.toString(VentanaMaestra.VARS_COTIZ.getFleteLocal()));
        fleteAfueraTxt.setText(Float.toString(VentanaMaestra.VARS_COTIZ.getFleteAfuera()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField factorPromoTxt;
    private javax.swing.JTextField fleteAfueraTxt;
    private javax.swing.JTextField fleteLocalTxt;
    private javax.swing.JTextField gananciaFijoTxt;
    private javax.swing.JTextField gananciaVariableTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tasaRecargoTxt;
    // End of variables declaration//GEN-END:variables

}
