/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdi.UI;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import com.backendless.exceptions.BackendlessFault;
import com.pdi.negocio.entidades.finales.Caja;
import com.pdi.negocio.entidades.finales.CantidadesBase;
import com.pdi.negocio.entidades.finales.PreciosBase;
import com.pdi.negocio.entidades.finales.VariablesCotizacion;
import com.pdi.util.General;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sastre
 */
public class VentanaMaestra extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMaestra
     */
    //Instancias de objetos utilizadas en varias ventanass
    public static Caja CAJA = new Caja();
    public static CantidadesBase CANT_BASE = new CantidadesBase();
    public static PreciosBase PRECIOS_BASE = new PreciosBase();
    public static VariablesCotizacion VARS_COTIZ = new VariablesCotizacion();

    //Instancias de las ventanas, para poder interactuar entre ellas
    public static EventosVentana eventosCurrent;
    public static CajaVentana cajaCurrent;

    public VentanaMaestra() {
        initComponents();
        initCAJA();
        initCANT_BASE();
        initPRECIOS_BASE();
        initVARS_COTIZ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Abrir Ventana");

        jMenuItem1.setText("Eventos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Aliados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Caja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Inventario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Inversiones");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Contabilidad");

        jMenuItem7.setText("Flujo de Caja");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Patrimonio");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Herramientas");

        jMenuItem9.setText("Informes");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Analisis de Inversiones");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Ganancia Promedio");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Precios Promedio");
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configuracion");

        jMenuItem13.setText("Actualizar Precios Base");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Modificar Cant Base");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Modificar Variables de Cotiz");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if (!EventosVentana.abierta) {
            EventosVentana v = new EventosVentana();
            jDesktopPane1.add(v);
            Dimension desktopDim = jDesktopPane1.getSize();
            v.setSize(desktopDim);
            System.out.println(desktopDim);
            v.setVisible(true);
            eventosCurrent = v;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (!ClientesVentana.abierta) {
            ClientesVentana v = new ClientesVentana();
            jDesktopPane1.add(v);
            Dimension desktopDim = jDesktopPane1.getSize();
            v.setSize(desktopDim);
            System.out.println(desktopDim);
            v.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (!AliadosVentana.abierta) {
            AliadosVentana v = new AliadosVentana();
            jDesktopPane1.add(v);
            Dimension desktopDim = jDesktopPane1.getSize();
            v.setSize(desktopDim);
            System.out.println(desktopDim);
            v.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (!CajaVentana.abierta) {
            CajaVentana v = new CajaVentana();
            jDesktopPane1.add(v);
            Dimension desktopDim = jDesktopPane1.getSize();
            v.setSize(desktopDim);
            System.out.println(desktopDim);
            v.setVisible(true);
            cajaCurrent = v;
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (!InventarioVentana.abierta) {
            InventarioVentana v = new InventarioVentana();
            jDesktopPane1.add(v);
            Dimension desktopDim = jDesktopPane1.getSize();
            v.setSize(desktopDim);
            v.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
      if (!CantidadesBaseVentana.abierta) {
            CantidadesBaseVentana v = new CantidadesBaseVentana();
            jDesktopPane1.add(v);
            v.setVisible(true);
      }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        if (!PreciosBaseVentana.abierta) {
            PreciosBaseVentana v = new PreciosBaseVentana();
            jDesktopPane1.add(v);
            v.setVisible(true);
      }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
          if (!VariablesCotizacionVentana.abierta) {
            VariablesCotizacionVentana v = new VariablesCotizacionVentana();
            jDesktopPane1.add(v);
            v.setVisible(true);
      } 
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMaestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMaestra().setVisible(true);
            }
        });
    }

    private void initCAJA() {
        Backendless.Persistence.of(Caja.class).findById(General.ID_CAJA,
                new AsyncCallback<Caja>() {

                    public void handleResponse(Caja cajaBackendless) {
                        
                        CAJA = cajaBackendless;
                        System.out.println("Caja cargada");
                      
                    }

                    public void handleFault(BackendlessFault bf) {
                        JOptionPane.showMessageDialog(VentanaMaestra.this, //Componente
                                bf.getMessage(), //Mensaje
                                "Error al cargar la caja", //Titulo
                                JOptionPane.WARNING_MESSAGE); //Imagen 

                    }
                });

    }

    private void initCANT_BASE() {
        Backendless.Persistence.of(CantidadesBase.class).findById(General.ID_CANT_BASE,
                new AsyncCallback<CantidadesBase>() {

                    public void handleResponse(CantidadesBase cantBaseBackendless) {
                      CANT_BASE = cantBaseBackendless;
                        System.out.println("Cantidades Base cargadas");
                        System.out.println(CANT_BASE.getCachaca());
                        
                    }

                    public void handleFault(BackendlessFault bf) {
                    JOptionPane.showMessageDialog(VentanaMaestra.this, //Componente
                                bf.getMessage(), //Mensaje
                                "Error al cargar las Cantidades Base", //Titulo
                                JOptionPane.WARNING_MESSAGE); //Imagen 
                    }
                });
    }
    
    private void initPRECIOS_BASE() {
        Backendless.Persistence.of(PreciosBase.class).findById(General.ID_PRECIOS_BASE,
                new AsyncCallback<PreciosBase>() {

                    public void handleResponse(PreciosBase preciosBaseBackendless) {
                      PRECIOS_BASE = preciosBaseBackendless;
                        System.out.println("Precios Base cargadas");
                        
                    }

                    public void handleFault(BackendlessFault bf) {
                    JOptionPane.showMessageDialog(VentanaMaestra.this, //Componente
                                bf.getMessage(), //Mensaje
                                "Error al cargar los Precios Base", //Titulo
                                JOptionPane.WARNING_MESSAGE); //Imagen 
                    }
                });
    }

    private void initVARS_COTIZ() {
        Backendless.Persistence.of(VariablesCotizacion.class).findById(General.ID_VARS_COTIZ,
                new AsyncCallback<VariablesCotizacion>() {

                    public void handleResponse(VariablesCotizacion varsCotizBackendless) {
                      VARS_COTIZ = varsCotizBackendless;
                        System.out.println("Variables Cotizacion cargadas");
                        
                    }

                    public void handleFault(BackendlessFault bf) {
                    JOptionPane.showMessageDialog(VentanaMaestra.this, //Componente
                                bf.getMessage(), //Mensaje
                                "Error al cargar las Variables Cotizacion", //Titulo
                                JOptionPane.WARNING_MESSAGE); //Imagen 
                    }
                });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
